### ISSUE TITLE
Write "Get started"

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/r2dii.match#136]
> I think we could make the documentation on this page https://2degreesinvesting.github.io/r2dii.match/ a bit longer, for example it could spell out what the override argument can be used for, etc. I'm familiar with what the code executes, and still would have enjoyed I think being talked through it a tiny bit more, to be sure I understood what the code was doing, etc. If you think that's relevant I can suggest some input on that (just talking the user a tiny bit more through what the code does)
> --@fpalandri

**Comment by maurolepore** [comment]
Commonly, the home page of a package-website shows minimim features -- just a teaser ([example](https://pkgdown.r-lib.org/index.html)), and more details are usually shown in Get started ([example](https://pkgdown.r-lib.org/articles/pkgdown.html)).

**Comment by Clare2D** [comment]
Hey, I think my comment here is related to this. I'm just testing r2dii.match as though I was a bank and have a few comments. 

1. The documentation isn't clear as to which columns should be compared. I assume it's name and name_ald. Perhaps the "matched" dataframe could be reduced to make it clearer - the user in Excel needs to then hide columns to improve the visibility which is theoretically fine, however could be simpler. 
2. Reviewing the matches, it seems it matches via the ultimate or the direct loantaker - which means a user needs to view 3 columns to ensure there is a match (unless I'm missing something!) perhaps this can just be the two columns next to one another identifying the match. - reviewing this now it is just the last 4 columns that one needs to compare right? Anyway, those were my unfiltered first impressions ;) 
3. There are 474 matches on a loan book of 321 loans - this is correct? I assume then one can group by either level (ultimate/direct)
Maybe add some lower scored matches into the demo loan book. With the filter of 0.9 I got 100% perfect matches - unless again there was an error in my process somehow. 

Otherwise, the instructions worked really well and I completed the process in less than 10mins. Looking good!! @jdhoffa thanks for the heads up on testing this.

**Comment by maurolepore** [comment]
@Clare2D thank you very much for taking the time to try this and write feedback! That's very useful.

**Comment by jdhoffa** [comment]
@Clare2D Thanks so much for the feedback! This is greatly appreciated. Responses below: 
1. Good point on the documentation, and we received similar feedback from @fpalandri. Will add an issue to update this, and make the entire user process more clear/ obvious. 
On the topic of returning fewer columns on the `matched` dataframe, I think this could be ok, however we will need to think of how to cache the data in practice. As it stands currently, `match_name()` was designed to not "lose" any of the data that was input from the `loanbook`. In this way, we don't need to worry about merging the validated result back into the loanbook, so we don't need to worry about saving the original `loanbook` data (in the global env for instance). I think once we begin working on the actual banks meta package/ analysis pipeline, we might make it more user-friendly, and could design write intermedaite data to the harddrive, but happy to discuss/ revisit this decision. 
2. So we have built in a "fail-safe" for this. As a user, you don't need to look at the `level` column at all. You can validate a match at `direct_loantaker`, `intermediate_parent` and `ultimate_parent` level simultaneously, and this is totally valid. The `prioritize()` function, which is meant to be run after you manually validate matches, will then pick any match with a `score=1` and in the user-defined prioritiy order (the default order is `direct_loantaker` >`intermediate_parent` > `ultimate_parent`). The point of this is to reduce the workload on the user, and ensure that the best match is always chosen automatically, even if the user fucks up. 
3. Related to 2. This is correct, and is a result of the possibility of there being multiple matches for the same loan, at various levels. Once you run the result of `match_name()` through `prioritize()` then the result and loanbook will have identical or fewer rows. 
As far as setting the threshold, the default threshold is `0.8`, (I'd prefer to keep this as the default, as a lot of people aren't going to change this, and in practice it's a good threshold for reasonable matches), but for demonstration purposes, you can manually set it less, to see what false matches might look like. (I can add a blurb about this in the README)
