### ISSUE TITLE
Add more helpful tests/error messages for horribly incorrect input

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#146]
Relates to 2DegreesInvesting/r2dii.dataraw#37

Currently, the package errors, but it is not clear why:
``` r
library(r2dii.dataraw)
#> Loading required package: r2dii.utils
library(r2dii.match)

suppressPackageStartupMessages(library(dplyr))

bad_loanbook <- loanbook_demo %>% 
  mutate(name_direct_loantaker = as.numeric(12))

bad_loanbook %>% match_name(ald_demo)
#> Error: No common type for `name_direct_loantaker` <double> and `name_intermediate_parent_1` <character>.
```

<sup>Created on 2020-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@maurolepore Could a datacheck be done using directly the `data_dictionary` table? (By ensuring, on input, that all `loanbook-like` etc. data.frames have the correct type as defined in `data_dictionary`)

**Comment by maurolepore** [comment]
Nice!

One way I solved this problem before was via a low level helper that gives the [columns specification](https://readr.tidyverse.org/reference/cols.html) (also [here](https://vroom.r-lib.org/reference/cols.html)) needed to read each dataset ([example](https://forestgeo.github.io/fgeo.tool/reference/type_vft.html)). We could also provide a `read_<dataset>()` helper for the user's convenience ([example](https://forestgeo.github.io/fgeo.tool/reference/read_vft.html)).

@jdhoffa, I think your idea is good of keeping this piece of knowledge DRY. My only suggestion is this:

Instead of capturing the info in `data_dictionary` then parsing it to construct the type specification, I would go the other way around. That is, each dataset contributed to dataraw should come with a type-specification object (for readr to use) that we could transform into the `typeof` column of `data_dictionary`.

**Comment by jdhoffa** [comment]
oh yes absolutely, i like that more
