### ISSUE TITLE
probably best to explicitly namespace imported functions

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.match#151]
Many dplyr and tibble functions are not namespaced in `match_name()`, for example...
https://github.com/2DegreesInvesting/r2dii.match/blob/9d3ed2ec726223e9edf09cc4850628038fbf3473/R/match_name.R#L82

**Comment by maurolepore** [comment]
Great you bring this up: To (always) namespace or when to namespace. that is the question :)

Here I describe my current approach, hoping @cjyetman and @jdhoffa will help us arrive to a decision we could use to develop an internal guideline.

I usually omit the namespace of functions used multiple times -- particularly the most common dplyr verbs and `group_by()`. I think the code becomes clearer because less words (e.g. `dplyr::`) make it easier to see the intent of the code at first glance. 

But  my approach makes it harder to move features to another package, and to know where functions come from. Also, it seems easier to follow the rule "always use the namespace" than the rule "use namespace when the function is used multiple times".

Opinions?

**Comment by jdhoffa** [comment]
Is there a standard best practice for this? (like do tidyverse packages explicitly namespace every dplyr funcion internally, or are they lax about repeated functions?) 

My, somewhat arbitrary, vote would be to reproduce that style

**Comment by maurolepore** [comment]
![namespace](https://user-images.githubusercontent.com/5856545/75775623-f6889a80-5d17-11ea-86f7-f9e66cc5ebef.png)

**Comment by maurolepore** [comment]
I'd like to discuss namespacing also in the context of analysis code -- not just packages. [I propose we continue this discussion at a ds-incubator meetup](https://github.com/2DegreesInvesting/ds-incubator/issues/11#issuecomment-593934579).
