### ISSUE TITLE
functions that are only used once

### ISSUE THREAD

**Issue by cjyetman** [2DegreesInvesting/r2dii.match#153]
While I support writing functions to do common tasks, I think it actually detracts from readability of the code when one line expressions are wrapped into a function and only used once elsewhere. For example...

https://github.com/2DegreesInvesting/r2dii.match/blob/9d3ed2ec726223e9edf09cc4850628038fbf3473/R/match_name.R#L149-L159

**Comment by maurolepore** [comment]
Thanks @cjyetman, 

I see what you mean and generally agree. But when I use a line in an uncommon way I feel like explaining (at least to myself) what I'm doing, and I prefer to capture that explanation in a meaningfully named function instead of a comment. 

This is one of those cases, where I'm using `rlang::set_names()` in a way that is a bit too clever:

``` r
x <- c(a = 1)

# This is easy to understand
rlang::set_names(x, "b")
#> b 
#> 1

# But this requires explanation, and instead of a comment I prefer a good name
rlang::set_names(x, paste0, "_suffix")
#> a_suffix 
#>        1
```

<sup>Created on 2020-03-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
