### ISSUE TITLE
`match_name()` with large data crashes the R session

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.match#214]
From an email with a bank:
> We ran the file you send and  came across this error while running the R script below, not sure how is the size becoming as 7.3gb – the ALD file size is around 100mb.

``` r
# Load libraries
library("r2dii.match") # For matching data
library("readxl") # For reading in excel sheets
library("readr") # For writing CSVs

# Read in your data
ald_demo <- read.csv("...")
loanbook_demo <- read_excel("...")

# Match data
matched_data = match_name(loanbook = loanbook_demo,
                          ald = ald_demo, 
                          min_score = 0.9)
```

yields the following error: 

``` r
Error: cannot allocate vector of size 7.3 Gb

In addition: Warning message:

Some `sector_classification_direct_loantaker` are unknown:

NA
```

**Comment by jdhoffa** [comment]
What I imagine is happening is the following: 
`match_name` full_joins `loanbook` and `ald`, calculates the fuzzy matching score between pairwise elements, and filters those above a threshold. This is not an optimized process at all, as we are effectively working with a dataset of size `~ nrow(loanbook) * nrow(ald)`. For very large datasets, this may cause memory allocation issues. 

Will think this over and see if there is a clever alternative today.

**Comment by maurolepore** [comment]
On 2020-07-10 @georgeharris2deg reports a similar issue while working at HSBC. I hope to capture his experience in this thread so we can use it to find a solution.

**Comment by maurolepore** [comment]
Surprisingly, a profiler showed that -- instead of join -- the slowest process was `unique()`. #226 replaced `unique()` with the faster `distinct()`, and also moved and removed calls to maximize speed. The result is much faster and I was able to successfully run `match_name()` with datasets of realistic size.

But #226 leaves a number of issues unsolved: 


* How to handle larger datasets?
* Does this work on windows?
* Should be compute off-memory (e.g. ff package)
* Does doing things in parallel help? What if we spread computation across multiple cores?
* What is the operation running when the program crashes?

**Comment by maurolepore** [comment]
I'm now learning more about how to interpret the results of the profiler. Here are some resources I'm liking:

* https://rstudio.github.io/profvis/examples.html#example-1
* https://rstudio.github.io/profvis/examples.html#example-2
* https://adv-r.hadley.nz/perf-measure.html

**Comment by maurolepore** [comment]
For the record, I'm considering removeing the argument `by_sector` so that `match_name()` always runs by sector. This saves computation, but it might be less than I had anticipated -- so I'm not convinced yet.


With the version on CRAN, which has the argument `by_sector`:

``` r
library(r2dii.data)

l <- rbind(loanbook_demo, loanbook_demo, loanbook_demo, loanbook_demo)
a <- head(ald_demo, 10000)

bench::mark(sec_F = r2dii.match::match_name(l, a, by_sector = FALSE))
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 sec_F         547ms    547ms      1.83        NA     9.14
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
  
 --

With one development version, which lacks the argument `by_sector`:
  
``` r
library(r2dii.data)

l <- rbind(loanbook_demo, loanbook_demo, loanbook_demo, loanbook_demo)
a <- head(ald_demo, 10000)

devtools::load_all()
#> Loading r2dii.match
bench::mark(sec_T = match_name(l, a))
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 sec_T         254ms    268ms      3.73        NA     11.2
```

<sup>Created on 2020-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by maurolepore** [comment]
For the record, most of the memory usage seems related to joins (see \<GC\> = Garbage Collector).

![image](https://user-images.githubusercontent.com/5856545/87684238-a1d64100-c747-11ea-8c1b-770b627d507f.png)


I'll see if it makes a difference to implement joins in data.table. I understand data.table more commonly uses data in-place instead of copying into memory.

https://atrebas.github.io/post/2019-03-03-datatable-dplyr/#join

**Comment by maurolepore** [comment]
Update

![image](https://user-images.githubusercontent.com/5856545/87800146-a6682b80-c813-11ea-99ec-4fb2ddd107b6.png)

**Comment by maurolepore** [comment]
This approach seems to use a lot less memory -- the calls to the garbage collector are less noticeable. This is likely because data.table modifies in place. This is with a loanbook of size 18MB and an ald of size 100 MB:


![image](https://user-images.githubusercontent.com/5856545/87826310-49359f80-c83e-11ea-94f0-b6ca3411f366.png)

**Comment by maurolepore** [comment]
Here I compare the version of `match_name()` in development versus the one on CRAN. I also explain what people should do when their data is too big. There will always be a limit.

https://2degreesinvesting.github.io/posts/2020-07-18-improving-r2dii-match/

![image](https://user-images.githubusercontent.com/5856545/87860814-1ce55600-c906-11ea-93d1-b6a42789fce4.png)
